# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 07:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_like',
            field=models.BooleanField(default=0),
        ),
    ]
