# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment_is_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='is_like',
            field=models.IntegerField(default=0),
        ),
    ]
