# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170216_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='viewers',
            field=models.IntegerField(default=0),
        ),
    ]
