# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 03:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20170217_1843'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercomment',
            old_name='unlike_count',
            new_name='like_unlike',
        ),
    ]
