# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 08:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20170218_0347'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercomment',
            name='post',
            field=models.ForeignKey(default=18, on_delete=django.db.models.deletion.CASCADE, to='blog.Post'),
            preserve_default=False,
        ),
    ]
